---
# DEFAULT CONFIGURATIONS WHICH CAN BE OVERRIDEN
# This directory will be created and will contain vagrant, application, scripts etc..
ANSIBLE_TMP_DIR: "~/ansible_artifacts"


# Application configurations ###################################################
# APPLICATION_PACKAGE_NAME      >> Name of the application package without the extension
# APPLICATION_FOLDER_NAME       >> Name of the application folder once it is expanded/unarchived
# APPLICATION_GZ_ARCHIVE_NAME   >> Name of the application archive
# APPLICATION_ARCHIVE_LOCATION  >> Location of the archive files
# APPLICATION_PORT              >> Port on which the application starts up
################################################################################
APPLICATION_NAME: "sample"

PREV_APPLICATION_VERSION: ""
PREV_APPLICATION_PACKAGE_NAME: "{{ APPLICATION_NAME }}-{{ PREV_APPLICATION_VERSION }}"
PREV_APPLICATION_FOLDER_NAME: "{{ PREV_APPLICATION_PACKAGE_NAME }}"
PREV_APPLICATION_GZ_ARCHIVE_NAME: "{{ PREV_APPLICATION_FOLDER_NAME }}.tar.gz"

APPLICATION_VERSION: "1.1-SNAPSHOT"
APPLICATION_PACKAGE_NAME: "{{ APPLICATION_NAME }}-{{ APPLICATION_VERSION }}"
APPLICATION_FOLDER_NAME: "{{ APPLICATION_PACKAGE_NAME }}"
APPLICATION_GZ_ARCHIVE_NAME: "{{ APPLICATION_FOLDER_NAME }}.tar.gz"
APPLICATION_ARCHIVE_LOCATION: "~/archives"
APPLICATION_PORT: 9876



# Vagrant Configurations ###################################################
# VAGRANT_FOLDER_NAME           >> Name of the vagrant folder once it is unarchived
# VAGRANT_ARCHIVE_NAME          >> Name of the vagrant archive
# VAGRANT_PACKAGE_LOCATION      >> Location of the archive file
################################################################################
VAGRANT_FOLDER_NAME: "vagrant"
VAGRANT_ARCHIVE_NAME: "{{ VAGRANT_FOLDER_NAME }}.tar.gz"
VAGRANT_PACKAGE_LOCATION: "~/archives"



# Vagrant Configurations ###################################################
# A dynamic inventory file is generated to be used by ansible for provisioning
# application and checking on its health
# DYNAMIC_INVENTORY_SCRIPT      >> Script file that is deployed by ansible into Guest machine
# DYNAMIC_INVENTORY_FILE        >> Inventory file that is generated by the python script
################################################################################
DYNAMIC_INVENTORY_SCRIPT: "vagrantToInventory.py"
DYNAMIC_INVENTORY_FILE: "dynamicVagrantInventory"

# Default Topology || Supported Topologies: w1h1, w1h2
TOPOLOGY: "w1h1" # Default topology
